service: planet-commercetools-connector

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - package/**

frameworkVersion: ">=2.11.1"

functions:
  allOperationsHandler:
    handler: app/environment-specific-handlers/aws-http/index.allOperationsHandler
    timeout: 5
    memorySize: 128
    events:
      - http:
          method: post
          path: ct-extension

  webhookNotificationHandler:
    # Use the same allOperationsHandler - it is not a typo, it's done intentionally (see README).
    handler: app/environment-specific-handlers/aws-http/index.allOperationsHandler
    timeout: 5
    memorySize: 128
    events:
      - http:
          method: post
          path: dt-webhook
