name: CI Pipeline
on: [push]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Get the codebase from the git repo
        uses: actions/checkout@v3
        
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check code quality (ESLint)
        run: npm run lint
        
      - name: Run tests
        run: npm run test
        
 #     - name: Test Reporter
 #       uses: vebr/jest-lcov-reporter@v0.2.0
 #       with:
 #         github-token: ${{ secrets.GITHUB_TOKEN }}
 #         lcov-file: coverage/lcov.info
          
      - name: Run build
        run: npm run build
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=planet 
            -Dsonar.projectKey=commerceTools 
            -Dsonar.sources=. 
            -Dsonar.testExecutionReportPaths=coverage/index.html
            -Dsonar.test.exclusions=test/**
            -Dsonar.tests=test/
            -Dsonar.typescript.tsconfigPath=tsconfig.json
            -Dsonar.eslint.reportPaths=lint-result.json
            -Dsonar.language=js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
      - name: Look at the build result
        run: find ./dist -name "*.js" -print
