name: lint-test-build-connector
on: [push]
jobs:
  lint-test-build:
    runs-on: macos-latest
    steps:
      - name: Get the codebase from the git repo
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Check code quality (ESLint)
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Run build
        run: npm run build
      - name: Look at the build result
        run: find ./dist -name "*.js" -print
